# syntax=docker/dockerfile:1

#
# Copyright (c) 2020-2021 Intel Corporation.
# SPDX-License-Identifier: BSD-3-Clause
#

# BROKEN BUILD DUE TU UPDATED VERSION OF BASEKIT
# INSTEAD THE MINI VERSION IS BEING BUILD USING
# OFFLINE INSTALLER

ARG IMAGE_CACHE_REGISTRY=docker.io
ARG IMAGE_NAME=intel/oneapi-basekit:2024.0.0-devel-rockylinux9
FROM ${IMAGE_CACHE_REGISTRY}/${IMAGE_NAME} AS build
RUN echo "ERROR!" && exit 1

ARG DL_PREFIX=/opt
ARG PREFIX=/opt/build
ARG LD_LIBRARY_PATH="/opt/build/lib:/opt/build/lib64:/usr/local/lib:/usr/local/lib64"
ARG FFMPEG_COMMIT_ID="n6.1.1"
ENV TZ="Europe/Warsaw"

ARG NASM_RPM_LINK="https://rpmfind.net/linux/centos-stream/9-stream/CRB/x86_64/os/Packages/nasm-2.15.03-7.el9.x86_64.rpm"

WORKDIR "${PREFIX}"
COPY . ${DL_PREFIX}/Video-Super-Resolution-Library

SHELL ["/bin/bash", "-ex", "-o", "pipefail", "-c"]
WORKDIR "${DL_PREFIX}/ffmpeg"
RUN yum install -y \
      wget bash \
      git make \
      cmake \
      glibc \
      bzip2 \
      zlib-devel && \
    wget --tries=5 --progress=dot:giga ${NASM_RPM_LINK} && \
    yum localinstall -y nasm-2.15.03-7.el9.x86_64.rpm && \
    rm -f nasm-2.15.03-7.el9.x86_64.rpm && \
    yum group list && \
    yum group install "Development Tools" -y && \
    yum clean all && \
    rm -rf /var/cache/yum

WORKDIR ${DL_PREFIX}/libx264
RUN git clone https://github.com/mirror/x264 -b stable --depth 1 . && \
    ./configure --prefix=${PREFIX} --libdir=${PREFIX}/lib --enable-shared && \
    make -j $(nproc) && \
    make install

WORKDIR ${DL_PREFIX}/libx265/build/linux
RUN curl -Lf https://github.com/videolan/x265/archive/3.4.tar.gz | \
      tar -zx --strip-components=1 -C "${DL_PREFIX}/libx265/" && \
    cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${PREFIX} -DHIGH_BIT_DEPTH=ON ../../source && \
    make -j$(nproc) && \
    make install

ENV IPPROOT="/opt/intel/oneapi/ipp/latest"
ENV IP_PPREFIX="/opt/intel/oneapi/ipp/latest"
ENV PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/opt/build/lib/pkgconfig"
ENV CPATH="${IPPROOT}/include:${IPPROOT}/include/ipp"
ENV IPP_TARGET_ARCH="intel64"
ENV LD_LIBRARY_PATH="/opt/build/lib:/opt/build/lib64:/usr/local/lib:/usr/local/lib64:${IPPROOT}/lib/intel64"
ENV LIBRARY_PATH="${IPPROOT}/lib/intel64"

WORKDIR ${DL_PREFIX}/Video-Super-Resolution-Library
RUN curl -Lf https://github.com/ffmpeg/ffmpeg/archive/${FFMPEG_COMMIT_ID}.tar.gz | \
      tar -zx --strip-components=1 -C "${DL_PREFIX}/ffmpeg" && \
    git -C "${DL_PREFIX}/ffmpeg" apply "${DL_PREFIX}/Video-Super-Resolution-Library/ffmpeg/"*.patch && \
    cp "${DL_PREFIX}/Video-Super-Resolution-Library/ffmpeg/vf_raisr"*.c "${DL_PREFIX}/ffmpeg/libavfilter" && \
    ./build.sh

WORKDIR ${DL_PREFIX}/ffmpeg
RUN ./configure \
      --enable-libipp \
      --extra-cflags="-fopenmp" \
      --extra-ldflags=-fopenmp\
      --enable-gpl \
      --enable-libx264 \
      --enable-libx265 \
      --extra-libs='-lraisr -lstdc++ -lippcore -lippvm -lipps -lippi' \
      --enable-cross-compile \
      --prefix="${PREFIX}"  && \
    make clean && \
    make -j $(nproc) && \
    make install && \
    rm -rf ${DL_PREFIX}/libx265 ${DL_PREFIX}/libx264

WORKDIR ${PREFIX}/usr/local/lib
RUN ldd ${PREFIX}/bin/ffmpeg | cut -d ' ' -f 3 | xargs -i cp {} . && \
    mv ${PREFIX}/bin ${PREFIX}/usr/local/ && \
    rm -rf ${PREFIX}/share ${PREFIX}/include ${PREFIX}/lib

ARG IMAGE_CACHE_REGISTRY
FROM ${IMAGE_CACHE_REGISTRY}/library/rockylinux:9@sha256:d7be1c094cc5845ee815d4632fe377514ee6ebcf8efaed6892889657e5ddaaa6 AS base

LABEL org.opencontainers.image.authors="milosz.linkiewicz@intel.com"
LABEL org.opencontainers.image.url="https://github.com/OpenVisualCloud/Video-Super-Resolution-Library"
LABEL org.opencontainers.image.title="Intel® Library for Video Super Resolution"
LABEL org.opencontainers.image.description="Intel® Library for Video Super Resolution. RAISR (Rapid and Accurate Image Super Resolution) algorithm implementation by Intel® Corporation, as FFmpeg plugin. Centos::stream9 image."
LABEL org.opencontainers.image.documentation="https://github.com/OpenVisualCloud/Video-Super-Resolution-Library/blob/main/README.md"
LABEL org.opencontainers.image.version="1.0.0"
LABEL org.opencontainers.image.vendor="Intel® Corporation"
LABEL org.opencontainers.image.licenses="BSD 3-Clause License"

ARG PREFIX=/opt/build
ENV TZ=Europe/Warsaw
ENV LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64:/opt/intel/oneapi/redist/lib
WORKDIR /opt/raisrfolder

COPY docker/Xeon/yum/oneAPI.repo /etc/yum.repos.d
RUN yum install -y \
        sudo \
        vim \
        bash \
        intel-oneapi-runtime-ipp && \
    yum clean all && \
    rm -rf /var/cache/yum && \
    groupadd -g 2110 vfio && \
    useradd -m -s /bin/bash -G vfio -u 1002 raisr && \
    usermod -aG wheel raisr

COPY --chown=raisr:raisr filters_1.5x /opt/raisrfolder/filters_1.5x
COPY --chown=raisr:raisr filters_2x   /opt/raisrfolder/filters_2x
COPY --chown=raisr:raisr --from=build ${PREFIX} /

RUN ln -s /usr/local/bin/ffmpeg /opt/raisrfolder/ffmpeg && \
    ldconfig && \
    ffmpeg -h filter=raisr

# x264-libs # x265-libs
# USER "raisr"
HEALTHCHECK --interval=30s --timeout=5s CMD ps aux | grep "ffmpeg" || exit 1

SHELL ["/bin/bash", "-c"]
CMD ["-h", "filter=raisr"]
ENTRYPOINT [ "/opt/raisrfolder/ffmpeg" ]
